pub mod chemistry;
pub mod hippocampus;
pub mod memory;
pub mod neocortex;
// pub mod phi_probe;
// pub mod gemma_probe;
pub mod reservoir;
pub mod thought;
pub mod llm;
pub mod memory_vector;
pub mod inner_voice;
pub mod quantized_gemma_raw;